import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}


/*
hukuk-sitesi/
 └─ app/
     ├─ page.js                # Ana sayfa (Slider, Hakkımızda, Hizmetler, Footer)
     ├─ globals.css            # Genel CSS (tema, font, renkler)
     └─ components/
         ├─ Navbar.js
         ├─ Slider.js
         ├─ About.js
         ├─ Services.js
         ├─ Footer.js
*/